# fly.toml app configuration file generated for boozefahrer on 2023-05-02T21:08:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "boozefahrer"
primary_region = "fra"
